---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: :rocket: gha"
    open-pull-requests-limit: 10
    # The actions in triage-issues.yml are updated in the Homebrew/.github repor

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
     interval: "weekly"
    commit-message:
     prefix: "fix: :rocket: docker"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: :rocket: npm for astro-docs"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: :rocket: pip"
