stages:
  - test
  - prepare
  - deploy

# Cache gems in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - vendor/jruby

variables:
  BUNDLE_JOBS: 10
  BUNDLE_PATH: vendor
  CI: 1
  PARALLEL: 1

.before_script: &before_script
  - ruby -v
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

ruby31:
  script:
    - brew install-bundler-gems
    - brew test-bot --only-cleanup-before
    - brew test-bot --only-setup
    - brew test-bot --only-tap-syntax
    - brew test-bot --only-formulae --only-json-tab --skip-recursive-dependents --root-url="https://ghcr.io/v2/jmuelbert/homebrew-qtifw"

  artifacts:
    paths:
      - coverage

coverage:
  stage: prepare
  dependencies:
    - ruby31
  image: 'ruby:3.2'
  before_script:
    - gem install simplecov --no-doc
  script:
    - find coverage -name "*resultset.json" -exec sed -i 's?/home?'`pwd`'?' {} \;
    - rake coverage:report
  artifacts:
    paths:
      - 'coverage/'

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mkdir public
    - mv coverage public/coverage
  only:
    - main
  artifacts:
    paths:
      - public
    expire_in: 30 days
