---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(.gitlab-ci.yml|\.github/labels\.yml|\.github/pr-labeler.\yml)'
BASH_FILTER_REGEX_EXCLUDE: '(lib)'
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|LICENSE|LICENSES/)'
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '(\.automation/generated|docs/descriptors)'
TYPESCRIPT_FILTER_REGEX_EXCLUDE: '(src/apps/translations)'
DOCKERFILE_HADOLINT_ARGUMENTS: '--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046'
REPOSITORY_TRIVY_ARGUMENTS:
  - '--skip-dirs'
  - '.automation/test'
SHOW_ELAPSED_TIME: true
EMAIL_REPORTER: false
FILEIO_REPORTER: true
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: true
PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
PRE_COMMANDS:
  - command: echo "This is MegaLinter PRE_COMMAND on own MegaLinter ! :)"
    cwd: 'root'
POST_COMMANDS:
  - command: echo "This is MegaLinter POST_COMMAND on own MegaLinter ! :)"
    cwd: 'workspace'
