default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-added-large-files
        args: ['--maxkb=150']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
        exclude: ^.*(\.cbproj|\.groupproj|\.props|\.sln|\.vcxproj|\.vcxproj.filters)$
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: end-of-file-fixer
        stages:
        - commit
        - manual
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages:
          - commit
          - manual
      - id: no-commit-to-branch
        args: [--branch, develop]
      - id: pretty-format-json
        args: ['--autofix']

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.0.2
    hooks:
        - id: bundler-audit
        - id: check-mailmap
        - id: fasterer
        - id: forbid-binary
        # -   id: forbid-space-in-indent
        - id: git-check
        - id: git-dirty
        # - id: markdownlint
        # - id: reek
        # -   id: require-ascii
        # - id: rubocop
        - id: script-must-not-have-extension
          name: Local policy is to exclude extension from all shell files
          types: [shell]
        - id: script-must-not-have-extension
          name: Executable Ruby scripts must not have a file extension
          types: [ruby, executable]
        - id: shellcheck
        - id: shfmt

  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0  # substitute a tagged version
    hooks:
      - id: doctoc
