# https://www.appveyor.com/docs/appveyor-yml/

version: '{build}'

# branches to build
branches:
  # allowlist
  only:
    - main
  except:
    - 'gh-pages'

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not build additional commits to feature branch with open Pull Requests
skip_branch_with_pr: true

# Start builds on tags only (GitHub, BitBucket, GitLab)
skip_non_tags: true

# Rolling builds
# can only be configured via UI: https://www.appveyor.com/docs/build-configuration/#rolling-builds

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu2004

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# cloning the repository happens here

install:
  - bundle install

environment:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

before_test:
  - ruby -v
  - which ruby
  - gem -v
  - bundle -v

build: false

test_script:
  - bundle install --jobs 3 --retry 3
  - bundle exec rake
  - bundle exec fastlane execute_tests
