---
# SPDX-FileCopyrightText: Jürgen Mülbert <juergen.muelbert@web.de>
#
# SPDX-License-Identifier: EUPL-1.2
name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    env:
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [3.0.2, head]

    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: Enable Brew on Ubuntu
        if: runner.os == 'Linux'
        run: echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> $GITHUB_PATH

      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: set up Brew
        run: |
          brew tap
          brew tap jmuelbert/qtifw
          brew tap

      - name: Install qtifw
        run: brew install qtifw --verbose --debug

      - name: Brew RuboCop
        run: brew test

  fastlaneChecks:
    name: fastlane env reminder
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: fastlane/github-actions/fastlane-env-reminder@latest
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN}}"

  changeLog:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
