name: commit-lint

on: [push, pull_request]

jobs:
  commit-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ahmadnassri/action-commit-lint@v2.0.8
        with:
          config: .github/linters/.commit-lint.yml
