name: Processing issues
on:
    issues:
        types: [opened]

jobs:
    fastlane-env:
        name: fastlane env reminder
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.5
            - uses: fastlane/github-actions/fastlane-env-reminder@latest
              with:
                  repo-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
