---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT
#
#
name: "GitHub Labeler"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labeler.yml"
      - ".github/workflows/labeler.yml"

permissions:
  contents: read

jobs:
  labeler:
    uses: jmuelbert/commons/.github/workflows/labeler.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPath:  ${{ secrets.envPAT }}
