---
# SPDX-FileCopyrightText: Jürgen Mülbert <juergen.muelbert@web.de>
#
# SPDX-License-Identifier: EUPL-1.2
#
name: Misspell fixer

on: [push, pull_request]

permissions:
  contents: read

jobs:
  misspell-fixer:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: sobolevn/misspell-fixer-action@master
      - name: "Check diff"
        run: git diff --exit-code ${{ github.sha }}
      - uses: peter-evans/create-pull-request@v5
        if: failure()
        with:
          commit-message: "Fix typos by misspell-fixer"
          title: "Fix typos by misspell-fixer for ${{ github.ref }}"
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: "auto-pr/misspell-fixer/${{ github.ref }}"
