---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT
#
#
name: "GitHub Labeler"

on:
  - pull_request_target

permissions:
  contents: read

jobs:
  labeler:
    uses: jmuelbert/commons/.github/workflows/pull-request.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
